### ISSUE TITLE
knative-kafka-instance.yaml is not in the intended directory

### ISSUE THREAD

**Issue by hupiper** [redhat-canada-gitops/catalog#26]
The kustomization file for the 4.7 overlay has this reference for a resource: 

resources:  - knative-kafka-instance.yaml

There is no file like that in the directory.

**Comment by strangiato** [comment]
This was resolved by #25 and merged a few hours ago so you should be good to go!

**Comment by hupiper** [comment]
Thanks for looking into that! I should have been more clear, I'm referencing the openshift-serverless-operator catalog entry.

I still get the same error because I am invoking the overlay this way: oc apply -k https://github.com/redhat-canada-gitops/catalog/openshift-serverless-operator/overlays/4.7, and the reference in that kustomization file is:

resources:  - knative-kafka-instance.yaml

There is no file like that in this catalog entry.

**Comment by strangiato** [comment]
Ah, I see.  Yeah, that was probably a left over copy and paste error when I set those up.  I went ahead and submitted a PR to fix that.

**Comment by pittar** [comment]
PR merged.  Thanks @hupiper for opening the issue, and thanks @strangiato for fixing it!
